### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by LastExile16** [ipfs/iptb-plugins#4]
`make install` results in this error:
`../../../../gx/ipfs/QmbK4EmM2Xx5fmbqK38TGP3PpY66r3tkXLZTcc7dF9mFwM/go-ipfs-config/serialize/serialize.go:13:2: cannot find package "github.com/facebookgo/atomicfile" in any of:
        /usr/local/go/src/github.com/facebookgo/atomicfile (from $GOROOT)
        /home/nawras/go/src/github.com/facebookgo/atomicfile (from $GOPATH)
Makefile:33: recipe for target 'install' failed
make: *** [install] Error 1`

**Comment by LastExile16** [comment]
Is this repository no longer supported?

**Comment by travisperson** [comment]
The `go-ipfs-config` package was just updated recently. Can you try building from the master branch again?

Also what version of `gx` and `gx-go` do you have installed?

**Comment by jdjkelly** [comment]
Same thing here. Seems to get through deps install fine though.
```
gx-go rw22] 0s
(cd iptb; go install)
../vendor/gx/ipfs/QmXctaABKwgzmQgNM4bucMJf7zJnxxvhmPM1Pw95dxUfB5/go-ipfs-config/serialize/serialize.go:13:2: cannot find package "github.com/facebookgo/atomicfile" in any of:
	/home/user/go/src/github.com/ipfs/iptb-plugins/vendor/github.com/facebookgo/atomicfile (vendor tree)
	/usr/lib/go-1.11/src/github.com/facebookgo/atomicfile (from $GOROOT)
	/home/user/go/src/github.com/facebookgo/atomicfile (from $GOPATH)
Makefile:33: recipe for target 'install' failed
make: *** [install] Error 1
```
Master is at `56bef0fa722f863055c3c72d5767204bd77da7f7` 

```
↪ go version                                                               [2] ✘
go version go1.11.1 linux/amd64

↪ gx --version
gx version 0.14.0

↪ gx-go --version
gx-go version 1.9.0
```

**Comment by LastExile16** [comment]
It works fine and smooth now. thanks

**Comment by jdjkelly** [comment]
Cleared vendor, tried again, worked -- not sure what happened here.

**Comment by travisperson** [comment]
Awesome! I'm going to close this issue now, as it appears everything is resolved.
