### ISSUE TITLE
Stale transitive dep for libp2p/go-libp2p-resource-manager

### ISSUE THREAD

**Issue by decentralgabe** [ipfs/iptb-plugins#53]
I am trying to use the IPFS plugin for my tests however get a compilation error like ...

> ../../../go/pkg/mod/github.com/libp2p/go-libp2p-resource-manager@v0.3.0/rcmgr.go:42:33: cannot use (*resourceManager)(nil) (value of type *resourceManager) as type "github.com/libp2p/go-libp2p/core/network".ResourceManager in variable declaration:
        *resourceManager does not implement "github.com/libp2p/go-libp2p/core/network".ResourceManager (wrong type for OpenConnection method)
                have OpenConnection(dir "github.com/libp2p/go-libp2p/core/network".Direction, usefd bool) ("github.com/libp2p/go-libp2p/core/network".ConnManagementScope, error)
                want OpenConnection(dir "github.com/libp2p/go-libp2p/core/network".Direction, usefd bool, endpoint multiaddr.Multiaddr) ("github.com/libp2p/go-libp2p/core/network".ConnManagementScope, error)

It appears [there is a stale indirect dependency](https://github.com/ipfs/iptb-plugins/blob/master/go.mod#L45). Would it be possible to update this to the new library [as outlined in the dep](https://github.com/libp2p/go-libp2p-resource-manager)?

**Comment by decentralgabe** [comment]
Manually updating the dep to `v0.4.0` fixed the issue too.

**Comment by guseggert** [comment]
This has been upgraded to v0.4.0 so this is no longer an issue
